### ISSUE TITLE
Return value when closed with escape or closeThisDialog()

### ISSUE THREAD

**Issue by grabbou** [likeastore/ngDialog#119]
When closed by escape or background click, return object from promise looks like below:

``` js
{$dialog: jQuery.fn.init[1], id: "ngdialog4", remainingDialogs: 1, value: "$document"}
```

I am quite unhappy that return value is '$document'. To me, it should be null in order to allow null checks when using without promises. For now - it it required to check both presence and string equality.

Value should be not null only when closed with closeThisDialog(value).

**Comment by chaddjohnson** [comment]
Agreed. I feel that $document should not be passed for "value".

**Comment by grabbou** [comment]
Yep, I couldn't understand my issue that much so I've rewritten it a bit. @voronianski @chaddjohnson

**Comment by voronianski** [comment]
@grabbou @chaddjohnson pull requests are welcome.

@colinbate as I remember you've introduced this feature?

**Comment by grabbou** [comment]
Also, when using promise pattern, IMO promise should be rejected when modal has been closed by background click or escape instead of being resolved positively with above options. 

Something like this is quite tricky:
```js
$modals.modifyImage(image).then(function(res) {
      if (_.isObject(res.value)) {}
});
```
I just need to check if res.value is an object so I can assume user confirmed its changes, otherwise promise is either rejected (user clicked my custom close button) or contains that string (user clicked in the background)

**Comment by grabbou** [comment]
<Update> I think it might be just because I misuse `.closePromise` attribute which is intended to be resolved no matter what happens (https://github.com/likeastore/ngDialog/pull/41) instead of doing openConfirm.

Sounds like there's no problem here then :)

**Comment by chaddjohnson** [comment]
@grabbou 

I'm not sure I agree. Here is what I'm doing:

```
var dialog = ngDialog.open({
    templateUrl: 'app/account/templates/editPasswordModal.html',
    controller: 'accountEditPasswordModalController',
    className: 'ngdialog-theme-default edit-password-modal'
});

dialog.closePromise.then(function(data) {
    if (data.value && data.value != '$document') {
        notification.show('success', 'Password was updated.');
    }
    else {
        notification.show('info', 'Password was not updated.');
    }

    return true;
});
```

As you can see, I need to handle two cases: 1) when the user cancels a modal and 2) when the user closes the modal "successfully".

What do you propose would be a better way to handle this?

**Comment by freeall** [comment]
@chaddjohnson The problem with that is that now we have to do that check everywhere we use the modal. Also from an architecture point of view it seems leaky that some state of the dialog finds it way into the data.

**Comment by colinbate** [comment]
As @grabbou mentioned, this scenario should be covered by `openConfirm()`.

For @chaddjohnson your example might look something like this:

```
ngDialog.openConfirm({
    templateUrl: 'app/account/templates/editPasswordModal.html',
    controller: 'accountEditPasswordModalController',
    className: 'ngdialog-theme-default edit-password-modal',
    closeByEscape: true, // Assuming you want the same closing abilities.
    closeByDocument: true
}).then(function() {
    notification.show('success', 'Password was updated.');
}).catch(function () {
    notification.show('info', 'Password was not updated.');
});
```

This is assuming that you use the scope's `confirm()` method in the success case within your application logic and the `closeThisDialog()` in any cancellation cases you may allow. Closing the dialog will already be considered rejections.

That said, when the value being resolved out of the promise was initially conceived it was strictly meeting the need of identifying how the dialog was closed, and it was assumed your application (or my application I guess) was handling the semantics of those possibilities in a single location. It certainly does make sense that since we are resolving a rich object with meta-data from the close promise that we could simply have boolean properties on that object such as `closedByEscape`, keeping that information out of `value` which can be reserved for application specific values passed from the managing controller, etc.
