### ISSUE TITLE
Prevent that enter keypress close the modal

### ISSUE THREAD

**Issue by elifio** [likeastore/ngDialog#152]
hello

I have two questions

My first question,happens in the demo too. is that once the modal open and while not get the focus this modal, open another instance of modal, being able to open many times.

Other issue is that once I have opened the modal form using an autocomplete, this autocomplete select the item by pressing enter and also launches the closing action (is the action of the first button)

I can avoid closing the form?

http://plnkr.co/edit/4aDGuv?p=preview

**Comment by XcodeJunkie** [comment]
Have a look at the angular description about submitting a form.
https://docs.angularjs.org/api/ng/directive/form#submitting-a-form-and-preventing-the-default-action

Be sure to

1. Have no `ng-submit` directive on your `form` tag
2. Submit your form with a `button` on `ng-click`. Button type should be `button` rather than `submit`.

Example:
`<form novalidate name="form">`
`<input type="text" ng-model="field1" name="field1" />`
`<input type="text" ng-model="field2" name="field2" />`
`<input type="button" ng-click="submitForm()" value="Submit me!"/>`
`</form>`
