### ISSUE TITLE
closePromise not works

### ISSUE THREAD

**Issue by mrbatista** [likeastore/ngDialog#261]
see [this](http://plnkr.co/edit/7KMkkmkLmIp42mPt9hjm?p=preview) Plunker for more details.

**Comment by egor-smirnov** [comment]
@mrbatista According to what I see in the plunker there is no way to trigger closing of dialog1 from UI (because for dialog1 `showClose` is false, `closeByEscape` is false, `closeByDocument` is false).

One possibility is to allow closing of dialog1 like here - http://plnkr.co/edit/5KUhpj9FzWJsj5qS6O4t?p=preview. Click on [x] button - `closePromise` will work.

**Comment by egor-smirnov** [comment]
Feel free to reopen issue if you have any further questions.
