### ISSUE TITLE
$(...).remove() must be called in tests

### ISSUE THREAD

**Issue by guy-mograbi-at-gigaspaces** [likeastore/ngDialog#263]
Hi, 

we recently started using ngDialog. great library!! keep the good work. very pleased. 

we just added several tests that verifies existence of elements on dialog (for example we verify close buttons exist..). at the end of each test we close the dialog with `ngDialog.closeAll()` verify that the dom elements are removed. something like

```
ngDialog.open...
expect($(...).length).toBe(1);
ngDialog.closeAll
expect($(...).length).toBe(0);
```

for some reason, element is still there and the second expect fails. 
we are currently removing the elements explicitly - to allow other tests to verify the same on other dialogs, otherwise the number of close buttons accumulate. 

this is what we are doing
```
elems.remove();
ngDialog.closeAll();
```

not sure if this is a bug or not, however it would be nice if elements were removed implicitly

**Comment by egor-smirnov** [comment]
I guess it's because dialog is not closed immediately due to this line - https://github.com/likeastore/ngDialog/blob/dcf24b307afa0f7574f0855bc9266410845f6683/js/ngDialog.js#L156. There dialog is not removed from the DOM until `animationend` is triggered. That's why your tests still sees dialog in the DOM.

One of solutions could be setting of option `disableAnimation` to `false`. See https://github.com/likeastore/ngDialog#disableanimation-boolean. Additionally, you could set `disabledAnimation` to `false` using `ngDialogProvider` - see https://github.com/likeastore/ngDialog#setdefaultsoptions.

P.S. And use version from master branch, not release version. This is because `disableAnimation` was added recently and is not published at npm / bower.

**Comment by egor-smirnov** [comment]
You could also take a look into tests inside ngDialog itself - https://github.com/likeastore/ngDialog/blob/master/tests/ngDialog.spec.js. There is not a lot of cases there, but it could be a bit inspirational.

**Comment by guy-mograbi-at-gigaspaces** [comment]
@egor-smirnov great advice.

i think we will simply add `afterEach` that will simply search and remove all ngDialog dom elements for now. once animation is available as a version we will try to replace. 

 perhaps there should be a note about testing in the documents. 

thanks.
