### ISSUE TITLE
ngDialog not working when used with templateCache, ngAnnotate and uglify

### ISSUE THREAD

**Issue by iaakash** [likeastore/ngDialog#283]
Here is what my Console says:
![ngdialog_error](https://cloud.githubusercontent.com/assets/1436589/8899809/ca0c7812-3456-11e5-94e5-1cff8788620e.jpg)

**Comment by razvanbalosin** [comment]
Have you tried @ngInject comment in your controller?

**Comment by egor-smirnov** [comment]
@iaakash could you provide some repo with minimal reproducible scenario? I could do it myself later but currently I don't have enough time for this.

**Comment by davidvuong** [comment]
Hey @iaakash,

I'm pretty confident this is a problem with ngAnnotate not correctly injecting dependencies rather than ngDialog. If you use Angular's array notation to inject dependencies you won't be seeing any problems with minification.

However, since you're using ngAnnotate, I believe there are times where you have to explicitly define an `ngInject` property for any provider, directive or controller that requires DI. Here's an example:

```js
/** @ngInject */
function myService(ngDialog) {
  ngDialog.open(...);
}

var app = angular.module('app', []);
app.service('myService', myService);
```

See https://github.com/olov/ng-annotate#explicit-annotations-with-nginject for more information. Hope this helps.

Anyway, I'm closing this issue due to the lack of activity and also because I think it's not an issue with ngDialog, but with your build setup.
