### ISSUE TITLE
flicker on close

### ISSUE THREAD

**Issue by mrbormeth** [likeastore/ngDialog#317]
Hey :smile: 

I noticed that the dialog flickers on close this bug can be reproduced on http://likeastore.github.io/ngDialog/

This commit should fix it https://github.com/likeastore/ngDialog/commit/104e04bb149f1b5f3b31e0ad70ce002f4064dd71

But now it seems that the overlay is flickering. 
Any quick workaround for this issue? 

Btw. thx for a EPIC dialog system for angular! :+1:

**Comment by mrbormeth** [comment]
I managed to fix it :+1: 

I noticed this commit. 

Regenerate stale build files
rur authored on 22 Apr

**Comment by planetparker** [comment]
THANK YOU for providing this fix.  I can't explain why over a year later, I have downloaded the most recent version (I think), but the issue still existed.  I had to manually provide your commit [(104e04b)](https://github.com/likeastore/ngDialog/commit/104e04bb149f1b5f3b31e0ad70ce002f4064dd71) in order to fix it for our version.  It was bugging the heck out of me, so thanks again for the css fix.
