### ISSUE TITLE
Override default template for close button

### ISSUE THREAD

**Issue by mrsidde** [likeastore/ngDialog#560]
Hi! 
Im trying change the default value/markup of the close button
`<button aria-label="Dismiss" class="ngdialog-close"></button>`

My plan is to use a svg, something like this: 
`<svg class="ngdialog-close >
  <ellipse class="custom-close" .../>
  <path class="" .../>
</svg>
`

Any idea how or if it's possible in the current version? 

Thanks in advance! 👍

**Comment by ghost** [comment]
while testing with JAWS for accessibility, the close/ dismiss button is not navigable by keyboard, on adding character within the button, it becomes navigable by keyboard. i'm assuming  &nbsp;  would work as well, alternatively, adding tabindex=0 might work too. but in order to try it out, we need a way to customize it. 

can this be taken up as priority?
